### ISSUE TITLE
require-python hides usefull python errors message

### ISSUE THREAD

**Issue by behrica** [clj-python/libpython-clj#159]
By doing this

```
(libpython-clj2.require/require-python '[top2Vec])
```

vs.
```
(py/import-module "top2vec")
```

the first hides the root cause of an issue with the module.
Only the `import-module`  prints this on the console:

```
Execution error at libpython-clj2.python/path->py-obj (python.clj:627).
Failed to find module or class top2Vec
Execution error at libpython-clj2.python.ffi/check-error-throw (ffi.clj:670).
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/top2vec/__init__.py", line 1, in <module>
    from top2vec.Top2Vec import Top2Vec
  File "/usr/local/lib/python3.9/site-packages/top2vec/Top2Vec.py", line 20, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

```

while `require-python` only gives this stacktrace:

```
 Unhandled java.lang.Exception
   Failed to find module or class top2Vec

                python.clj:  627  libpython-clj2.python/path->py-obj
                python.clj:  608  libpython-clj2.python/path->py-obj
               RestFn.java:  439  clojure.lang.RestFn/invoke
               require.clj:  109  libpython-clj2.require/do-require-python
               require.clj:   86  libpython-clj2.require/do-require-python
               require.clj:  273  libpython-clj2.require/require-python/fn
               require.clj:  265  libpython-clj2.require/require-python
               require.clj:  173  libpython-clj2.require/require-
```

**Comment by jjtolton** [comment]
For clarification, does this occur from Python as well or only in
libpython-clj?

**Comment by cnuernber** [comment]
I can confirm this happens.  There is a try/catch in there in a perhaps inappropriate place.  The work is to distiguish between attributes that won't load that we warn about and failures that we report to the user.

**Comment by jjtolton** [comment]
Whoops, still requires some work.  I forgot all the magic we were doing here
