### ISSUE TITLE
[main] ERROR libpython-clj2.python.ffi - Exception while releasing object clojure.lang.Compiler$CompilerException

### ISSUE THREAD

**Issue by BuddhiLW** [clj-python/libpython-clj#222]
How could I solve such error?

```shell
$ java --version
openjdk 18.0.2 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+0)
OpenJDK 64-Bit Server VM (build 18.0.2+0, mixed mod
e)
```

```shell
$ whereis java
java: /usr/bin/java /usr/share/java /usr/lib/jvm/java-18-openjdk/bin/java
```

```shell
$ clojure --version
Clojure CLI version 1.11.1.1165
```

My `project.clj`,
```clojure
(defproject practical-deep-learning2022 "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}

  :dependencies [[org.clojure/clojure "1.11.1"]
                 [techascent/tech.ml.dataset "6.100"]
                 [clj-python/libpython-clj "2.019"]]

  :repl-options {:init-ns practical-deep-learning2022.config})
```

My `practical-deep-learning2022.config`,
```clojure
(ns practical-deep-learning2022.config
  (:require [libpython-clj2.python :as py]))

(py/initialize!)
```

The error at the initial repl, 
```
14:56:15.610 [main] INFO libpython-clj2.python.info - Detecting startup info
14:56:15.667 [main] INFO libpython-clj2.python - Startup info {:lib-version "3.10", :java-library-path-addendum "/home/buddhilw/.conda/envs/deeplearning/lib", :exec-prefix "/home/buddhilw/.conda/envs/deeplearning", :executable "/home/buddhilw/.conda/envs/deeplearning/bin/python3", :libnames ("python3.10m" "python3.10"), :prefix "/home/buddhilw/.conda/envs/deeplearning", :base-prefix "/home/buddhilw/.conda/envs/deeplearning", :libname "python3.10m", :base-exec-prefix "/home/buddhilw/.conda/envs/deeplearning", :python-home "/home/buddhilw/.conda/envs/deeplearning", :version [3 10 4], :platform "linux"}
14:56:15.667 [main] INFO libpython-clj2.python - Prefixing java library path: /home/buddhilw/.conda/envs/deeplearning/lib
14:56:15.774 [main] INFO libpython-clj2.python - Loading python library: python3.10
14:56:16.402 [main] DEBUG libpython-clj2.python.ffi - Initializing Python C Layer
14:56:16.405 [tech.resource.gc ref thread] INFO tech.v3.resource.gc - Reference thread starting
14:56:16.406 [main] DEBUG libpython-clj2.python.ffi - Python Home: /home/buddhilw/.conda/envs/deeplearning
14:56:16.427 [main] INFO tech.v3.datatype.nio-buffer - Unable to find direct buffer constructor -
falling back to jdk16 memory model.
14:56:16.432 [main] ERROR libpython-clj2.python.ffi - Exception while releasing object
clojure.lang.Compiler$CompilerException: Syntax error macroexpanding at (tech/v3/datatype/ffi/nio_buf_mmodel.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7665)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$serialized_require.invokeStatic(core.clj:6114)
	at clojure.core$requiring_resolve.invokeStatic(core.clj:6123)
	at clojure.core$requiring_resolve.invoke(core.clj:6117)
	at tech.v3.datatype.nio_buffer$fn__8352.invokeStatic(nio_buffer.clj:104)
	at tech.v3.datatype.nio_buffer$fn__8352.invoke(nio_buffer.clj:95)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at tech.v3.datatype.nio_buffer$native_buf__GT_nio_buf.invokeStatic(nio_buffer.clj:113)
	at tech.v3.datatype.nio_buffer$native_buf__GT_nio_buf.invoke(nio_buffer.clj:108)
	at libpython_clj2.python.ffi$pystr__GT_str.invokeStatic(ffi.clj:790)
	at libpython_clj2.python.ffi$pystr__GT_str.invoke(ffi.clj:778)
	at libpython_clj2.python.ffi$pytype_name.invokeStatic(ffi.clj:798)
	at libpython_clj2.python.ffi$pytype_name.invoke(ffi.clj:794)
	at libpython_clj2.python.ffi$pyobject_type_kwd$reify__8985.apply(ffi.clj:814)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at libpython_clj2.python.ffi$pyobject_type_kwd.invokeStatic(ffi.clj:810)
	at libpython_clj2.python.ffi$pyobject_type_kwd.invoke(ffi.clj:807)
	at libpython_clj2.python.ffi$simplify_or_track.invokeStatic(ffi.clj:954)
	at libpython_clj2.python.ffi$simplify_or_track.invoke(ffi.clj:946)
	at libpython_clj2.python.fn$call_py_fn.invokeStatic(fn.clj:197)
	at libpython_clj2.python.fn$call_py_fn.invoke(fn.clj:177)
	at libpython_clj2.python.fn$eval9810$fn__9811.invoke(fn.clj:203)
	at libpython_clj2.python.protocols$eval9303$fn__9304$G__9292__9313.invoke(protocols.clj:67)
	at libpython_clj2.python.fn$call.invokeStatic(fn.clj:211)
	at libpython_clj2.python.fn$call.doInvoke(fn.clj:208)
	at clojure.lang.RestFn.invoke(RestFn.java:460)
	at libpython_clj2.python.class$create_class$fn__10047.invoke(class.clj:83)
	at libpython_clj2.python.class$create_class.invokeStatic(class.clj:80)
	at libpython_clj2.python.class$create_class.invoke(class.clj:72)
	at libpython_clj2.python.io_redirect$fn__10837$fn__10838.invoke(io_redirect.clj:23)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at libpython_clj2.python.io_redirect$fn__10837.invokeStatic(io_redirect.clj:22)
	at libpython_clj2.python.io_redirect$fn__10837.invoke(io_redirect.clj:22)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at libpython_clj2.python.io_redirect$setup_std_writer$fn__10847.invoke(io_redirect.clj:50)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at libpython_clj2.python.io_redirect$setup_std_writer.invokeStatic(io_redirect.clj:48)
	at libpython_clj2.python.io_redirect$setup_std_writer.invoke(io_redirect.clj:44)
	at libpython_clj2.python.io_redirect$redirect_io_BANG_.invokeStatic(io_redirect.clj:58)
	at libpython_clj2.python.io_redirect$redirect_io_BANG_.invoke(io_redirect.clj:56)
	at libpython_clj2.python$initialize_BANG_$fn__10878.invoke(python.clj:107)
	at libpython_clj2.python$initialize_BANG_.invokeStatic(python.clj:100)
	at libpython_clj2.python$initialize_BANG_.doInvoke(python.clj:46)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at practical_deep_learning2022.config$eval11145.invokeStatic(config.clj:4)
	at practical_deep_learning2022.config$eval11145.invoke(config.clj:4)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval5.invokeStatic(form-init3446868902658346065.clj:1)
	at user$eval5.invoke(form-init3446868902658346065.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.Compiler.loadFile(Compiler.java:7591)
	at clojure.main$load_script.invokeStatic(main.clj:475)
	at clojure.main$init_opt.invokeStatic(main.clj:477)
	at clojure.main$init_opt.invoke(main.clj:477)
	at clojure.main$initialize.invokeStatic(main.clj:508)
	at clojure.main$null_opt.invokeStatic(main.clj:542)
	at clojure.main$null_opt.invoke(main.clj:539)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: java.lang.ClassNotFoundException: jdk.incubator.foreign.MemoryAddress
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at clojure.lang.RT.classForName(RT.java:2209)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2222)
	at tech.v3.datatype.ffi.nio_buf_mmodel$eval14183$loading__6789__auto____14184.invoke(nio_buf_mmodel.clj:1)
	at tech.v3.datatype.ffi.nio_buf_mmodel$eval14183.invokeStatic(nio_buf_mmodel.clj:1)
	at tech.v3.datatype.ffi.nio_buf_mmodel$eval14183.invoke(nio_buf_mmodel.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	... 124 common frames omitted
#error {
 :cause jdk.incubator.foreign.MemoryAddress
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error macroexpanding at (tech/v3/datatype/ffi/nio_buf_mmodel.clj:1:1).
   :data #:clojure.error{:phase :execution, :line 1, :column 1, :source tech/v3/datatype/ffi/nio_buf_mmodel.clj}
   :at [clojure.lang.Compiler load Compiler.java 7665]}
  {:type java.lang.ClassNotFoundException
   :message jdk.incubator.foreign.MemoryAddress
   :at [java.net.URLClassLoader findClass URLClassLoader.java 445]}]
 :trace
 [[java.net.URLClassLoader findClass URLClassLoader.java 445]
  [clojure.lang.DynamicClassLoader findClass DynamicClassLoader.java 69]
  [java.lang.ClassLoader loadClass ClassLoader.java 588]
  [clojure.lang.DynamicClassLoader loadClass DynamicClassLoader.java 77]
  [java.lang.ClassLoader loadClass ClassLoader.java 521]
  [java.lang.Class forName0 Class.java -2]
  [java.lang.Class forName Class.java 488]
  [java.lang.Class forName Class.java 467]
  [clojure.lang.RT classForName RT.java 2209]
  [clojure.lang.RT classForNameNonLoading RT.java 2222]
  [tech.v3.datatype.ffi.nio_buf_mmodel$eval14183$loading__6789__auto____14184 invoke nio_buf_mmodel.clj 1]
  [tech.v3.datatype.ffi.nio_buf_mmodel$eval14183 invokeStatic nio_buf_mmodel.clj 1]
  [tech.v3.datatype.ffi.nio_buf_mmodel$eval14183 invoke nio_buf_mmodel.clj 1]
  [clojure.lang.Compiler eval Compiler.java 7194]
  [clojure.lang.Compiler eval Compiler.java 7183]
  [clojure.lang.Compiler load Compiler.java 7653]
  [clojure.lang.RT loadResourceScript RT.java 381]
  [clojure.lang.RT loadResourceScript RT.java 372]
  [clojure.lang.RT load RT.java 459]
  [clojure.lang.RT load RT.java 424]
  [clojure.core$load$fn__6908 invoke core.clj 6161]
  [clojure.core$load invokeStatic core.clj 6160]
  [clojure.core$load doInvoke core.clj 6144]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invokeStatic core.clj 5933]
  [clojure.core$load_one invoke core.clj 5928]
  [clojure.core$load_lib$fn__6850 invoke core.clj 5975]
  [clojure.core$load_lib invokeStatic core.clj 5974]
  [clojure.core$load_lib doInvoke core.clj 5953]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invokeStatic core.clj 669]
  [clojure.core$load_libs invokeStatic core.clj 6016]
  [clojure.core$load_libs doInvoke core.clj 6000]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 669]
  [clojure.core$require invokeStatic core.clj 6038]
  [clojure.core$require doInvoke core.clj 6038]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$serialized_require invokeStatic core.clj 6114]
  [clojure.core$requiring_resolve invokeStatic core.clj 6123]
  [clojure.core$requiring_resolve invoke core.clj 6117]
  [tech.v3.datatype.nio_buffer$fn__8352 invokeStatic nio_buffer.clj 104]
  [tech.v3.datatype.nio_buffer$fn__8352 invoke nio_buffer.clj 95]
  [clojure.lang.Delay deref Delay.java 42]
  [clojure.core$deref invokeStatic core.clj 2337]
  [clojure.core$deref invoke core.clj 2323]
  [tech.v3.datatype.nio_buffer$native_buf__GT_nio_buf invokeStatic nio_buffer.clj 113]
  [tech.v3.datatype.nio_buffer$native_buf__GT_nio_buf invoke nio_buffer.clj 108]
  [libpython_clj2.python.ffi$pystr__GT_str invokeStatic ffi.clj 790]
  [libpython_clj2.python.ffi$pystr__GT_str invoke ffi.clj 778]
  [libpython_clj2.python.ffi$pytype_name invokeStatic ffi.clj 798]
  [libpython_clj2.python.ffi$pytype_name invoke ffi.clj 794]
  [libpython_clj2.python.ffi$pyobject_type_kwd$reify__8985 apply ffi.clj 814]
  [java.util.concurrent.ConcurrentHashMap computeIfAbsent ConcurrentHashMap.java 1708]
  [libpython_clj2.python.ffi$pyobject_type_kwd invokeStatic ffi.clj 810]
  [libpython_clj2.python.ffi$pyobject_type_kwd invoke ffi.clj 807]
  [libpython_clj2.python.ffi$simplify_or_track invokeStatic ffi.clj 954]
  [libpython_clj2.python.ffi$simplify_or_track invoke ffi.clj 946]
  [libpython_clj2.python.fn$call_py_fn invokeStatic fn.clj 197]
  [libpython_clj2.python.fn$call_py_fn invoke fn.clj 177]
  [libpython_clj2.python.fn$eval9810$fn__9811 invoke fn.clj 203]
  [libpython_clj2.python.protocols$eval9303$fn__9304$G__9292__9313 invoke protocols.clj 67]
  [libpython_clj2.python.fn$call invokeStatic fn.clj 211]
  [libpython_clj2.python.fn$call doInvoke fn.clj 208]
  [clojure.lang.RestFn invoke RestFn.java 460]
  [libpython_clj2.python.class$create_class$fn__10047 invoke class.clj 83]
  [libpython_clj2.python.class$create_class invokeStatic class.clj 80]
  [libpython_clj2.python.class$create_class invoke class.clj 72]
  [libpython_clj2.python.io_redirect$fn__10837$fn__10838 invoke io_redirect.clj 23]
  [clojure.lang.AFn applyToHelper AFn.java 152]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$with_bindings_STAR_ invokeStatic core.clj 1990]
  [clojure.core$with_bindings_STAR_ doInvoke core.clj 1990]
  [clojure.lang.RestFn invoke RestFn.java 425]
  [libpython_clj2.python.io_redirect$fn__10837 invokeStatic io_redirect.clj 22]
  [libpython_clj2.python.io_redirect$fn__10837 invoke io_redirect.clj 22]
  [clojure.lang.Delay deref Delay.java 42]
  [clojure.core$deref invokeStatic core.clj 2337]
  [clojure.core$deref invoke core.clj 2323]
  [libpython_clj2.python.io_redirect$setup_std_writer$fn__10847 invoke io_redirect.clj 50]
  [clojure.lang.AFn applyToHelper AFn.java 152]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$with_bindings_STAR_ invokeStatic core.clj 1990]
  [clojure.core$with_bindings_STAR_ doInvoke core.clj 1990]
  [clojure.lang.RestFn invoke RestFn.java 425]
  [libpython_clj2.python.io_redirect$setup_std_writer invokeStatic io_redirect.clj 48]
  [libpython_clj2.python.io_redirect$setup_std_writer invoke io_redirect.clj 44]
  [libpython_clj2.python.io_redirect$redirect_io_BANG_ invokeStatic io_redirect.clj 58]
  [libpython_clj2.python.io_redirect$redirect_io_BANG_ invoke io_redirect.clj 56]
  [libpython_clj2.python$initialize_BANG_$fn__10878 invoke python.clj 107]
  [libpython_clj2.python$initialize_BANG_ invokeStatic python.clj 100]
  [libpython_clj2.python$initialize_BANG_ doInvoke python.clj 46]
  [clojure.lang.RestFn invoke RestFn.java 397]
  [practical_deep_learning2022.config$eval11145 invokeStatic config.clj 4]
  [practical_deep_learning2022.config$eval11145 invoke config.clj 4]
  [clojure.lang.Compiler eval Compiler.java 7194]
  [clojure.lang.Compiler load Compiler.java 7653]
  [clojure.lang.RT loadResourceScript RT.java 381]
  [clojure.lang.RT loadResourceScript RT.java 372]
  [clojure.lang.RT load RT.java 459]
  [clojure.lang.RT load RT.java 424]
  [clojure.core$load$fn__6908 invoke core.clj 6161]
  [clojure.core$load invokeStatic core.clj 6160]
  [clojure.core$load doInvoke core.clj 6144]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invokeStatic core.clj 5933]
  [clojure.core$load_one invoke core.clj 5928]
  [clojure.core$load_lib$fn__6850 invoke core.clj 5975]
  [clojure.core$load_lib invokeStatic core.clj 5974]
  [clojure.core$load_lib doInvoke core.clj 5953]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invokeStatic core.clj 669]
  [clojure.core$load_libs invokeStatic core.clj 6016]
  [clojure.core$load_libs doInvoke core.clj 6000]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 669]
  [clojure.core$require invokeStatic core.clj 6038]
  [clojure.core$require doInvoke core.clj 6038]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [user$eval5 invokeStatic form-init3446868902658346065.clj 1]
  [user$eval5 invoke form-init3446868902658346065.clj 1]
  [clojure.lang.Compiler eval Compiler.java 7194]
  [clojure.lang.Compiler eval Compiler.java 7183]
  [clojure.lang.Compiler eval Compiler.java 7183]
  [clojure.lang.Compiler load Compiler.java 7653]
  [clojure.lang.Compiler loadFile Compiler.java 7591]
  [clojure.main$load_script invokeStatic main.clj 475]
  [clojure.main$init_opt invokeStatic main.clj 477]
  [clojure.main$init_opt invoke main.clj 477]
  [clojure.main$initialize invokeStatic main.clj 508]
  [clojure.main$null_opt invokeStatic main.clj 542]
  [clojure.main$null_opt invoke main.clj 539]
  [clojure.main$main invokeStatic main.clj 664]
  [clojure.main$main doInvoke main.clj 616]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 705]
  [clojure.main main main.java 40]]}
nREPL server started on port 37831 on host localhost - nrepl://localhost:37831
```

**Comment by BuddhiLW** [comment]
Oh, and about my python environment, in case needed:

```shell
pip freeze -v
```

Output:

```shell
aiohttp==3.8.3
aiosignal==1.2.0
async-timeout==4.0.2
attrs==22.1.0
blis==0.7.8
catalogue==2.0.8
certifi @ file:///opt/conda/conda-bld/certifi_1663615672595/work/certifi
charset-normalizer==2.1.1
click==8.1.3
confection==0.0.2
contourpy==1.0.5
cycler==0.11.0
cymem==2.0.6
datasets==2.5.1
dill==0.3.5.1
fastai==2.7.9
fastbook==0.0.28
fastcore==1.5.27
fastdownload==0.0.7
fastprogress==1.0.3
filelock==3.8.0
fonttools==4.37.3
frozenlist==1.3.1
fsspec==2022.8.2
graphviz==0.20.1
huggingface-hub==0.10.0
idna==3.4
Jinja2==3.1.2
joblib==1.2.0
kiwisolver==1.4.4
langcodes==3.3.0
libpython==0.2
MarkupSafe==2.1.1
matplotlib==3.6.0
mkl-fft==1.3.1
mkl-random @ file:///home/builder/ci_310/mkl_random_1641843545607/work
mkl-service==2.4.0
multidict==6.0.2
multiprocess==0.70.13
murmurhash==1.0.8
numpy==1.23.3
packaging==21.3
pandas==1.5.0
pathy==0.6.2
Pillow==9.2.0
preshed==3.0.7
pyarrow==9.0.0
pydantic==1.9.2
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.2.1
PyYAML==6.0
regex==2022.9.13
requests==2.28.1
responses==0.18.0
scikit-learn==1.1.2
scipy==1.9.1
sentencepiece==0.1.97
six @ file:///tmp/build/80754af9/six_1644875935023/work
smart-open==5.2.1
spacy==3.4.1
spacy-legacy==3.0.10
spacy-loggers==1.0.3
srsly==2.4.4
thinc==8.1.2
threadpoolctl==3.1.0
tokenizers==0.12.1
torch==1.12.1
torchvision==0.13.1
tqdm==4.64.1
transformers==4.22.2
typer==0.4.2
typing_extensions==4.3.0
urllib3==1.26.12
wasabi==0.10.1
xxhash==3.0.0
yarl==1.8.1
```

**Comment by BuddhiLW** [comment]
I'm in Arch Linux. I had installed many versions of java, guessing the version I was using was the problem.

Naively, I didn't know I should change it, or I could change it - more accurately -, through `archlinux-java` script, which is shipped with java, when installed in Arch.

```shell
$ archlinux-java status
Available Java environments:
  java-11-graalvm
  java-11-openjdk
  java-17-graalvm
  java-18-openjdk (default)
  java-19-jdk
  java-19-openjdk-bin
``` 

Then, 
```shell
sudo archlinux-java set java-11-graalvm
```

I run clojure again, and was able to get it running. So, my conclusion is, `java-18-openjdk` is incompatible at the moment with the package (interesting piece of advice for Arch users).

Documentation consulted: https://wiki.archlinux.org/title/java

**Comment by cnuernber** [comment]
This library only supports jdk's 8, 11, and 17.  The foreign memory module has changed every JDK version since jdk-16, so we are going to wait until it has stabilized or until the next LTS java version to update.
